### ISSUE TITLE
test-webserver.py: Fail while creating server certificate

### ISSUE THREAD

**Issue by ip6li** [ip6li/crypt-fetch#4]
test-webserver.py: Fail while creating server certificate.

```
Traceback (most recent call last):
  File "./test-webserver.py", line 1205, in <module>
    create_server_certs()
  File "./test-webserver.py", line 702, in create_server_certs
    create_server_certs_enc()
  File "./test-webserver.py", line 673, in create_server_certs_enc
    server_keystore["crt"] = sign_csr(key_pair_rsa["pub"], dn, [], True)
  File "./test-webserver.py", line 567, in sign_csr
    exec_cmd(cmd)
  File "./test-webserver.py", line 433, in exec_cmd
    raise err
  File "./test-webserver.py", line 428, in exec_cmd
    res = subprocess.run(cmd, capture_output=True, check=True)
  File "/usr/local/Cellar/python/3.7.6_1/Frameworks/Python.framework/Versions/3.7/lib/python3.7/subprocess.py", line 512, in run
    output=stdout, stderr=stderr)
```

**Comment by ip6li** [comment]
0322eeb801bf0f0aff28ff8b9893fac85e87490a
